---
- hosts: cdt
  remote_user: root
  vars:
    destdir: /root/ansible
    srcdir: ../../dist
  tasks:

  - name: Copy docker config to {{destdir}}
    copy: src={{srcdir}}/docker-compose-{{ip}}.yaml dest={{destdir}}/docker-compose.yaml
          force=true

  - name: boot
    shell: docker-compose -f {{destdir}}/docker-compose.yaml up -d

  # - name: boot
  #   shell: docker-compose -f {{destdir}}/docker-compose.yaml up -d




