common: &common
  version: cdt
  network: ansible_default
  mountpath: /root/ansible/nfs
  dnsserver: 192.168.0.25

client:
  cryptopath: benchmarks/config_raft
  usecmd: false
  orgs: 
    - org1
    - org2
    # - org3
    # - org4
fabric-network:
  peer:
    peer0.org1.example.com:  
      <<: *common
      host: 192.168.0.123
      port: 7051
    peer1.org1.example.com:  
      <<: *common
      host: 192.168.0.123
      port: 7061
    peer0.org2.example.com:  
      <<: *common
      host: 192.168.0.137
      port: 7051
    peer1.org2.example.com:  
      <<: *common
      host: 192.168.0.137
      port: 7061
  
  orderer:
    orderer0.example.com:  
      <<: *common
      host: 192.168.0.96
      port: 7050
    orderer1.example.com:  
      <<: *common
      host: 192.168.0.96
      port: 8050
    orderer2.example.com:  
      <<: *common
      host: 192.168.0.96
      port: 9050

  ca:
    ca.org1.example.com:  
      <<: *common
      host: 192.168.0.96
      port: 7054
    ca.org2.example.com:  
      <<: *common
      host: 192.168.0.96
      port: 8054
